# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [2]:
import main
import math
import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [3]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [4]:
def cylinder_area(r:float,h:float):
    
    if r<0 or h<0:
        return np.Nan 
    pole = 2* math.pi * r**2 + 2*math.pip *r*h
    return pole

In [21]:
main.cylinder_area(2,3)

62.83185307179586

In [22]:
main.cylinder_area(-2,3)

nan

Komentarz:
Zastosowano wzór na pole walca, jeśli wystąpi nieprawidłowość we wprowadzonych danych, funkcja zwraca "nan" z biblioteki numphy.

***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [23]:

ciag_arrange = np.arange(0, 5, 0.5)
print("Wynik z arange:")
print(ciag_arrange)

ciąg_linspace = np.linspace(0,5,11)
print("Wynik z linspace:")
print(ciąg_linspace)

Wynik z arange:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Wynik z linspace:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


Komentarz:
W zadaniu poznano dwie nowe funkcje z biblioteki numphy: arrange oraz linspace. Funkcja arrange ma następującą konstrukcję: arrange(start,koniec,skok). Warto dodać, że koniec jest to zakres <start,stop), dlatego wynik powyżej z arrange(0,5,0.5) kończy się na wartości 4.5. Funkcja linspace różni się konstrukcją w taki sposób: linspace(start,koniec, liczba wartości jakie chcemy wygenerować). Zakres jest obustronnie domknięty <start,koniec>, a liczby generują się w równych odstępach.

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [7]:
def fib(n: int):
    if n is None or not isinstance(n, int) or n < 0:
        return None
    if n == 0:
        return None
    if n == 1:
        return np.array([1])
    
    wynik = [1, 1]
    for i in range(2, n):
        wynik.append(wynik[i-1] + wynik[i-2])
    return np.array(wynik).reshape(1, -1)


In [8]:
main.fib(1)

array([1])

Komentarz:
Zaimplentowane zostało działanie funkcji fibonacciego, które było wielokrotnie modyfikowane, aby funkcja przeszła wszystkie testy. Warto zwrócić uwagę, że wynik zaczyna się od [1,1] dla liczb większych niż 2, a nie od [0,1]. Kolejną zmianą było dodanie warunku na to, że wprowadzona liczba musi być liczbą naturalną, aby działa funkcja. W innym przpadku zwraca None.
Następnie mamy pętle for, w której jest funkcja .append. Z niewiadomych dla mnie powodów zapsianie tego jako wynik[i]=wynik[i-1] + wynik[i-2] nie zdawało testów.
Zwracana jest tablica przy pomocy funkcji np.array z biblioteki numphy. Na sam koniec dodano, również .reshape(1,-1), gdzie 1 to liczba wierszy, którą ma mieć zmieniona tablica, a -1 to liczba kolumn, która automatycznie się dopasowywuje(argument -1 to powoduje). Funkcja sama w sobie konwertuje macierz ułożoną w kokretny sposób na inny jej zapis z zachowaniem kolejności.

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [9]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

In [10]:
def matrix_calculations(a:float):
    M = np.array([
            [a, 1, -a],
            [0, 1, 1],
            [-a, a, 1]
        ])
    Mdet = np.linalg.det(M)
    if Mdet ==0:
        Minv = np.nan
    else:
        Minv = np.linalg.inv(M)
    Mt = np.transpose(M)

    return (Minv, Mt, Mdet)

In [11]:
matrix_calculations(2)

(array([[ 0.125,  0.625, -0.375],
        [ 0.25 ,  0.25 ,  0.25 ],
        [-0.25 ,  0.75 , -0.25 ]]),
 array([[ 2,  0, -2],
        [ 1,  1,  2],
        [-2,  1,  1]]),
 np.float64(-7.999999999999998))

W zadaniu użyto funkcji det z biblioteki linalg. Wpierw tworzymy wskaznik macierzy. Jeśli jest różny od zera, to można stworzyć macierz odwrotną poprzez użycie funcji inv. Na koniec utworzony transpozycję macierzy, a całość zwrócono jako krotkę.

***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [12]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

In [13]:
M = np.array([
    [3, 1, -2, 4],
    [0, 1, 1, 5],
    [-2, 1, 1, 6],
    [4, 3, 0, 1]
])
element11 = M[0, 0]
element33 = M[2, 2]
element32 = M[2, 1]

w1 = M[:,2]
w2 = M[1,:]

print(f"Element M11: {element11}")
print(f"Element M23: {element33}")
print(f"Element M32: {element32}")
print(w1)
print(w2)


Element M11: 3
Element M23: 1
Element M32: 1
[-2  1  1  0]
[0 1 1 5]


Zainicjalizowano zadaną tablicę, przy pomocy np.array, a następnie przypisano do elementów oraz wektorów konkretne wartości. Na koniec wszystkie zostały one wypisane.

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [14]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [15]:
def custom_matrix(m:int, n:int):
    m = int(m)
    n = int(n)

    if (2 <= m <= 10) and (2 <= n <= 10):
        M = np.zeros( ( m, n ), dtype = int)
        for i in range(m):
            for j in range(n):
                if i > j:
                    M[i, j] = i
                else:
                    M[i, j] = j
        return M

In [16]:
custom_matrix(3,5)

array([[0, 1, 2, 3, 4],
       [1, 1, 2, 3, 4],
       [2, 2, 2, 3, 4]])

Komentarz: Testy nie przechodziły dla wartości <3,7> i po zwiększeniu zakresu na <2,10> testy przechodziły. Test sprawdzał wartości np. dla m=9 i n=9 i podawał wartość zamiast None, stąd ta zmiana w moim kodzie.

***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [17]:
v1 = np.array([1,3,13])
v2 = np.array([8,5,-2])
wynik1= 4*v1
wynik2=-v2 + np.array([2,2,2])
wynik3=np.dot(v1,v2)
wynik4=np.multiply(v1,v2)
print(wynik1)
print(wynik2)
print(wynik3)
print(wynik4)


[ 4 12 52]
[-6 -3  4]
-3
[  8  15 -26]


Zainicjalizowano dwa wektory, a następnie wykonano na nich operacje: mnożenia, dodawania, mnożenia Hadamarda oraz macierzy.

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [18]:
M1=np.array([[1,-7,3],[-12,3,4],[5,13,-3]])
v1 = np.array([1,3,13])
v2 = np.array([8,5,-2])

wynik1=3*M1
wynik2=3*M1 + np.array([[1,1,1],[1,1,1],[1,1,1]]) 
wynik2prim= 3*M1 + np.ones((3,3))
wynik3=np.transpose(M1)
wynik4= np.dot(M1,v1)
wynik5=np.dot((np.transpose(v2)),M1)
print(f"wynik 1. to\n {wynik1}\n")
print(f"wynik 2. to\n {wynik2}\n")
print(f"wynik 2prim. to\n {wynik2prim}\n")
print(f"wynik 3. to\n {wynik3}\n")
print(f"wynik 4. to\n {wynik4}\n")
print(f"wynik 5. to\n {wynik5}\n")

wynik 1. to
 [[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]]

wynik 2. to
 [[  4 -20  10]
 [-35  10  13]
 [ 16  40  -8]]

wynik 2prim. to
 [[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]]

wynik 3. to
 [[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]]

wynik 4. to
 [19 49  5]

wynik 5. to
 [-62 -67  50]



Zainicjalizowano zadaną macierz z polecenia, a następnie wykonano z nią operacje dodawania, mnożenia, transponate. Po drodze trzebabyło stworzyć macierz jednostkową, która wykonałem na dwa sposoby: np.ones(x,x) oraz jako np.array

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)